Fix: coming soon page
AfterClass-io/afterclass.io-v2 pull request #197
Opened 2024-07-22 12:52 UTC by whoisdavidd

fix: Coming-soon page
1. Fix the box based on the figma
2. Figma size and actual size not the same because when i follow the figma size not what i want
3. Ignore the user modal
4. Dark mode and light mode working (need help on how to import from the theme component)
5. Am i parameterize it correctly?

2024-07-25 15:04 UTC, whoisdavidd commented
with love with regards with besties and friend 
weee

2024-07-27 06:35 UTC, whoisdavidd commented
removed the alert modal, psuh only contains the coming soon page

2024-07-28 05:06 UTC, davidlhw requested changes
thank you for the changes! a couple of comments to be addressed before merging -

seems like the build is failing due to some unused variables

![image](https://github.com/user-attachments/assets/c8427c23-2579-4e13-8344-594b86f41cc2)

2024-07-28 05:06 UTC, davidlhw commented on src/common/components/NoticeCard/NoticeCard.tsx
> +export default NoticeCard;
issue: default exports are heavily discouraged, see google's [typescript style guide](https://google.github.io/styleguide/tsguide.html#exports) for more details

2024-07-28 05:06 UTC, davidlhw commented on src/common/components/NoticeCard/NoticeCardError/ErrorNoticeCard.tsx
issue(non-blocking): ideally, this should be the same component as the `<NoticeCard/>` component as they share the same structure, just with different styling as variants

however, since this is outside of the task's scope (much appreciated attempt nonetheless :D), we can leave it as-is (if you want) and work on it under #167

2024-07-28 05:06 UTC, davidlhw commented on src/common/components/Sidebar/Sidebar.tsx
question: unintentional changes?

2024-07-28 05:06 UTC, davidlhw commented on src/common/styles/components.scss
question: unintentional changes?

2024-07-30 15:55 UTC, whoisdavidd commented
bruh vercel hates me

2024-07-31 15:39 UTC, davidlhw approved these changes
thank you for the changes! we can work on the error card separately :)

2024-07-31 15:40 UTC, merged